class BusinessCategories {
  static const List<String> top100 = [
    'Acupuncturist',
    'Adoption Agency',
    'Air Conditioning Contractor',
    'Animal Hospital',
    'Appliance Repair Service',
    'Architect',
    'Assisted Living Facility',
    'Attorney',
    'Auto Body Shop',
    'Auto Repair Shop',
    'Bakery',
    'Bank',
    'Bar',
    'Barber Shop',
    'Beauty Salon',
    'Bicycle Shop',
    'Body Shop',
    'Bookkeeping Service',
    'Boutique',
    'Breakfast Restaurant',
    'Bridal Shop',
    'Cafe',
    'Car Dealer',
    'Car Wash',
    'Carpet Cleaning Service',
    'Caterer',
    'Cell Phone Store',
    'Chiropractor',
    'Cleaning Service',
    'Coffee Shop',
    'Computer Repair Service',
    'Contractor',
    'Counselor',
    'Dance School',
    'Day Care Center',
    'Dentist',
    'Dermatologist',
    'Divorce Lawyer',
    'Dog Trainer',
    'Dry Cleaner',
    'Electrician',
    'Estate Planning Attorney',
    'Event Venue',
    'Eye Care Center',
    'Family Practice Physician',
    'Financial Planner',
    'Fitness Center',
    'Florist',
    'Furniture Store',
    'Garage Door Supplier',
    'Garden Center',
    'General Contractor',
    'Gift Shop',
    'Glass Repair Service',
    'Gym',
    'Hair Salon',
    'Handyman',
    'Health Club',
    'Heating Contractor',
    'Home Inspector',
    'Hotel',
    'HVAC Contractor',
    'Insurance Agency',
    'Interior Designer',
    'Investment Service',
    'Italian Restaurant',
    'Jewelry Store',
    'Landscaper',
    'Lawyer',
    'Locksmith',
    'Marketing Agency',
    'Massage Therapist',
    'Medical Clinic',
    'Medical Spa',
    'Mental Health Clinic',
    'Mortgage Broker',
    'Moving Company',
    'Nail Salon',
    'Optometrist',
    'Orthodontist',
    'Painter',
    'Paving Contractor',
    'Personal Trainer',
    'Pest Control Service',
    'Pet Groomer',
    'Pet Store',
    'Pharmacy',
    'Photographer',
    'Physical Therapist',
    'Pizza Restaurant',
    'Plumber',
    'Podiatrist',
    'Property Management Company',
    'Psychologist',
    'Real Estate Agency',
    'Restaurant',
    'Roofing Contractor',
    'Self Storage Facility',
    'Solar Energy Contractor',
    'Spa',
    'Tanning Salon',
    'Tire Shop',
    'Tree Service',
    'Urgent Care Center',
    'Veterinarian',
    'Wedding Planner',
    'Weight Loss Center',
    'Window Cleaning Service',
    'Yoga Studio',
  ];
}
